name: Node.js CI

on:
  push:
    branches:
      - main       # Trigger for pushes to the main branch
  pull_request:
    branches:
      - main       # Trigger for pull requests to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

   
    steps:
    # Step 1: Checkout the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Node.js environment
    - name: Set up Node.js 18
      uses: actions/setup-node@v2
      with:
        node-version: 18
     
    # Step 3: Install dependencies
    - name: Install dependencies
      run: npm install

    - name: Run 
      run: npm run start
