name: Node.js CI

on:
  push:
    branches:
      - main       # Trigger for pushes to the main branch
  pull_request:
    branches:
      - main       # Trigger for pull requests to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16, 18]  # Set up a matrix for different Node.js versions

    steps:
    # Step 1: Checkout the code
    - name: Checkout code
      uses: actions/checkout@v2

    # Step 2: Set up Node.js environment
    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        registry-url: https://registry.npmjs.org/  # Set npm registry URL for publishing

    # Step 3: Install dependencies
    - name: Install dependencies
      run: npm install

    - name: Run 
      run: npm run start
